version: '3'
services:
  db:
    image: postgres
  webpacker:
    build: .
    command: bundle exec bin/webpack-dev-server
    volumes:
      - .:/tg_chat
    ports:
      - "8080:8080"
  web:
    build: .
    command: bundle exec rails s -p 5000 -b '0.0.0.0'
    volumes:
      - .:/tg_chat
    ports:
      - "5000:5000"
    depends_on:
      - db